nodeLinker: node-modules

packageExtensions:
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - checksum: f64f64b9a20d959e1bd1e723b78d3a2b0c37f7d853a5ebedf0720ae197b5ee139555307514f3ebc13a3f981f7f9b402e88147061350a7e2660241e58629097fa
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.43.cjs
