[formatter]

[formatter.nix]
command = "alejandra"
excludes = ["yarn-project.nix"]
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
includes = ["*.md", "*.toml", "*.yaml"]
excludes = ["packages/cardano-services/config/network/*"]
options = ["--plugin", "prettier-plugin-toml", "--write"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-i", "2", "-s", "-w"]
