global:
  scrape_interval: 15s
  scrape_timeout: 12s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: coroot-pg-agent
    static_configs:
      - targets: ['pg-agent:80']
