x-from-sdk: &from-sdk
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 10
  restart: on-failure
  volumes:
    - ../..:/app

x-logging: &logging
  logging:
    driver: 'json-file'
    options:
      max-size: '400k'
      max-file: '20'

x-projector: &projector
  build:
    context: ../../
    target: projector
  depends_on:
    ogmios:
      condition: service_healthy

x-provider-server: &provider-server
  build:
    args:
      - NETWORK=${NETWORK:-mainnet}
    context: ../../
    target: provider-server
  depends_on:
    cardano-db-sync:
      condition: service_started

x-with-postgres: &with-postgres
  depends_on:
    postgres:
      condition: service_healthy
  secrets:
    - postgres_password
    - postgres_user
    - postgres_db
    - postgres_db_asset
    - postgres_db_db_sync
    - postgres_db_handle
    - postgres_db_stake_pool
    - postgres_db_wallet_api

x-projector-environment: &projector-environment
  API_URL: http://0.0.0.0:3000
  BLOCKS_BUFFER_LENGTH: ${BLOCKS_BUFFER_LENGTH:-10}
  DROP_SCHEMA: ${DROP_PROJECTOR_SCHEMA:-false}
  POSTGRES_HOST: postgres
  POSTGRES_POOL_MAX: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_PORT: 5432
  POSTGRES_USER_FILE: /run/secrets/postgres_user
  SYNCHRONIZE: ${SYNCHRONIZE:-true}

x-provider-server-environment: &provider-server-environment
  API_URL: http://0.0.0.0:3000
  CARDANO_NODE_CONFIG_PATH: /config/cardano-node/config.json
  DB_CACHE_TTL: ${DB_CACHE_TTL:-120}
  DISABLE_DB_CACHE: ${DISABLE_DB_CACHE:-false}
  DISABLE_STAKE_POOL_METRIC_APY: ${DISABLE_STAKE_POOL_METRIC_APY:-false}
  ENABLE_METRICS: ${ENABLE_METRICS:-false}
  EPOCH_POLL_INTERVAL: ${EPOCH_POLL_INTERVAL:-500}
  SERVICE_NAMES: ${SERVICE_NAMES:-chain-history,network-info,rewards,stake-pool,tx-submit,utxo}
  SUBMIT_API_URL: ${SUBMIT_API_URL:-http://cardano-submit-api:8090/}
  USE_BLOCKFROST: ${USE_BLOCKFROST:-false}
  USE_SUBMIT_API: ${USE_SUBMIT_API:-false}
  ASSET_PROVIDER: ${ASSET_PROVIDER:-dbsync}
  UTXO_PROVIDER: ${UTXO_PROVIDER:-dbsync}
  CHAIN_HISTORY_PROVIDER: ${CHAIN_HISTORY_PROVIDER:-dbsync}
  REWARDS_PROVIDER: ${REWARDS_PROVIDER:-dbsync}
  NETWORK_INFO_PROVIDER: ${NETWORK_INFO_PROVIDER:-dbsync}
  TX_SUBMIT_PROVIDER: ${TX_SUBMIT_PROVIDER:-submit-node}
  STAKE_POOL_PROVIDER: ${STAKE_POOL_PROVIDER:-dbsync}
  NETWORK: ${NETWORK:-mainnet}
  BLOCKFROST_API_KEY: ${BLOCKFROST_API_KEY}
  BLOCKFROST_CUSTOM_BACKEND_URL: ${BLOCKFROST_CUSTOM_BACKEND_URL}

x-sdk-environment: &sdk-environment
  LOGGER_MIN_SEVERITY: ${LOGGER_MIN_SEVERITY:-info}
  NETWORK_INFO_PROVIDER_URL: http://provider-server:3000/
  OGMIOS_URL: ws://ogmios:1337
  OVERRIDE_FUZZY_OPTIONS: true
  POSTGRES_DB_FILE_ASSET: /run/secrets/postgres_db_asset
  POSTGRES_DB_FILE_DB_SYNC: /run/secrets/postgres_db_db_sync
  POSTGRES_DB_FILE_HANDLE: /run/secrets/postgres_db_handle
  POSTGRES_DB_FILE_STAKE_POOL: /run/secrets/postgres_db_stake_pool
  POSTGRES_DB_FILE_WALLET_API: /run/secrets/postgres_db_wallet_api
  POSTGRES_HOST_DB_SYNC: postgres
  POSTGRES_HOST_ASSET: postgres
  POSTGRES_HOST_HANDLE: postgres
  POSTGRES_HOST_STAKE_POOL: postgres
  POSTGRES_HOST_WALLET_API: postgres
  POSTGRES_POOL_MAX_DB_SYNC: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_POOL_MAX_HANDLE: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_POOL_MAX_ASSET: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_POOL_MAX_STAKE_POOL: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_POOL_MAX_WALLET_API: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_PASSWORD_FILE_ASSET: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_DB_SYNC: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_HANDLE: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_STAKE_POOL: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_WALLET_API: /run/secrets/postgres_password
  POSTGRES_PORT_DB_SYNC: 5432
  POSTGRES_PORT_ASSET: 5432
  POSTGRES_PORT_HANDLE: 5432
  POSTGRES_PORT_STAKE_POOL: 5432
  POSTGRES_PORT_WALLET_API: 5432
  POSTGRES_USER_FILE_ASSET: /run/secrets/postgres_user
  POSTGRES_USER_FILE_DB_SYNC: /run/secrets/postgres_user
  POSTGRES_USER_FILE_HANDLE: /run/secrets/postgres_user
  POSTGRES_USER_FILE_STAKE_POOL: /run/secrets/postgres_user
  POSTGRES_USER_FILE_WALLET_API: /run/secrets/postgres_user
  TOKEN_METADATA_SERVER_URL: https://metadata.world.dev.cardano.org
  USE_WEB_SOCKET_API: true
  WEB_SOCKET_API_URL: ws://ws-server:3000/ws

services:
  blockfrost-ryo:
    build:
      context: "https://github.com/ginnun/blockfrost-backend-ryo.git#feat/custom-network-support"
      dockerfile: Dockerfile
    environment:
      BLOCKFROST_CONFIG_SERVER_LISTEN_ADDRESS: 0.0.0.0
    depends_on:
      cardano-db-sync:
        condition: service_started
    ports:
      - "3015:3000"

  cardano-db-sync:
    <<:
      - *logging
      - *with-postgres
    command: ['--config', '/config/cardano-db-sync/config.json', '--socket-path', '/node-ipc/node.socket']
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RESTORE_SNAPSHOT: ${RESTORE_SNAPSHOT:-}
      RESTORE_RECREATE_DB: N
    depends_on:
      ogmios:
        condition: service_healthy
    image: ghcr.io/intersectmbo/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.5.0.1}
    restart: on-failure
    stop_signal: SIGINT
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc

  cardano-smash:
    <<:
      - *logging
      - *with-postgres
    image: ghcr.io/intersectmbo/cardano-smash-server:${CARDANO_DB_SYNC_VERSION:-13.5.0.1}
    command: ['--config', '/config/cardano-db-sync/config.json']
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RESTORE_SNAPSHOT: ${RESTORE_SNAPSHOT:-}
      RESTORE_RECREATE_DB: N
      SMASH_USER: ${SMASH_USER:-admin}
      SMASH_PASSWORD: ${SMASH_PASSWORD:-change_m}
    depends_on:
      cardano-db-sync:
        condition: service_started
    ports:
      - ${SMASH_PORT:-3100}:3100
    restart: on-failure
    stop_signal: SIGINT
    healthcheck:
      test: ['CMD-SHELL', 'curl -s --fail http://localhost:3100/api/v1/status']

  cardano-node:
    <<: *logging
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION:-9.1.1}
    command:
      [
        'run',
        '--config',
        '/config/config.json',
        '--database-path',
        '/db',
        '--socket-path',
        '/ipc/node.socket',
        '--topology',
        '/config/topology.json'
      ]
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc

  ogmios:
    <<: *logging
    image: cardanosolutions/ogmios:v${OGMIOS_VERSION:-6.5.0}
    command:
      [
        '--host',
        '0.0.0.0',
        '--node-socket',
        '/ipc/node.socket',
        '--node-config',
        '/config/cardano-node/config.json',
        '--log-level-websocket',
        'Warning',
        '--include-cbor'
      ]
    depends_on:
      cardano-node:
        condition: service_started
    healthcheck:
      retries: 2000
    ports:
      - ${OGMIOS_PORT:-1340}:1337
    restart: on-failure
    volumes:
      - node-ipc:/ipc

  cardano-submit-api:
    command: --config /config/cardano-submit-api/config.json --listen-address 0.0.0.0 --socket-path /ipc/node.socket $SUBMIT_API_ARGS
    image: ghcr.io/intersectmbo/cardano-submit-api:${CARDANO_NODE_VERSION:-9.1.1}
    ports:
      - 8090:8090
    restart: on-failure
    stop_signal: SIGINT
    volumes:
      - node-ipc:/ipc

  pg-boss-worker:
    <<:
      - *from-sdk
      - *logging
      - *with-postgres
    build:
      context: ../../
      target: pg-boss-worker
    depends_on:
      stake-pool-projector:
        condition: service_healthy
      cardano-smash:
        condition: service_healthy
    environment:
      <<: *sdk-environment
      API_URL: http://0.0.0.0:3003
      QUEUES: ${QUEUES:-pool-delist-schedule,pool-metadata,pool-metrics,pool-rewards}
      SCHEDULES: ${SCHEDULES:-/config/schedules.json}
      STAKE_POOL_PROVIDER_URL: http://provider-server:3000/
      METADATA_FETCH_MODE: ${METADATA_FETCH_MODE:-smash}
      SMASH_URL: ${SMASH_URL:-http://cardano-smash:3100/api/v1}
    ports:
      - ${PG_BOSS_PORT:-4003}:3003

  postgres:
    <<: *logging
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_LOGGING: true
      POSTGRES_DB_FILE: /run/secrets/postgres_db_db_sync
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: postgres:${POSTGRES_VERSION:-12.16-alpine}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - ${POSTGRES_PORT:-5435}:5432
    restart: on-failure
    secrets:
      - postgres_db_db_sync
      - postgres_password
      - postgres_user
    shm_size: '2gb'

  asset-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_asset
      PROJECTION_NAMES: asset
    ports:
      - ${ASSET_PROJECTOR_PORT:-4006}:3000

  handle-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_handle
      PROJECTION_NAMES: handle
    ports:
      - ${HANDLE_PROJECTOR_PORT:-4004}:3000

  stake-pool-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_stake_pool
      PROJECTION_NAMES: stake-pool,stake-pool-metadata-job,stake-pool-metrics-job,stake-pool-rewards-job
    ports:
      - ${STAKE_POOL_PROJECTOR_PORT:-4002}:3000

  wallet-api-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_wallet_api
      PROJECTION_NAMES: protocol-parameters
    ports:
      - ${WALLET_API_PROJECTOR_PORT:-4005}:3000

  provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
    ports:
      - ${API_PORT:-4000}:3000

  stake-pool-provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    depends_on:
      stake-pool-projector:
        condition: service_healthy
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
      SERVICE_NAMES: stake-pool
      USE_TYPEORM_STAKE_POOL_PROVIDER: true
    ports:
      - ${STAKE_POOL_API_PORT:-4010}:3000

  asset-provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    depends_on:
      asset-projector:
        condition: service_healthy
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
      SERVICE_NAMES: asset
      USE_TYPEORM_ASSET_PROVIDER: true
    ports:
      - ${HANDLE_API_PORT:-4014}:3000

  handle-provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    depends_on:
      handle-projector:
        condition: service_healthy
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
      SERVICE_NAMES: handle
    ports:
      - ${HANDLE_API_PORT:-4011}:3000

  ws-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    build:
      args:
        - NETWORK=${NETWORK:-mainnet}
      context: ../../
      target: ws-server
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
    ports:
      - ${WS_SERVER_PORT:-4100}:3000
    restart: always
    volumes:
      - ../..:/app

secrets:
  # Replicates the db-sync secret for historical reasons.
  # When the SDK was using only one database (the db-sync one) the only secret for database name used was this one
  # to be compliant with db-sync image naming.
  # The upstream db-sync Docker image is missing environment variables that allow the consumer to mount into a
  # non-standard path, so we must conform with the hard-coded secret name.
  # As demonstrated here: https://docs.docker.com/compose/use-secrets/#advanced, we could extend the Docker image
  # and define POSTGRES_DB_FILE as the custom path to remove this workaround.
  # See https://github.com/input-output-hk/cardano-db-sync/blob/aed18d1be192bd58d054cdba23758b579dae9f4e/nix/docker.nix#L116
  postgres_db:
    file: ../../compose/placeholder-secrets/postgres_db_db_sync
  postgres_db_asset:
    file: ../../compose/placeholder-secrets/postgres_db_asset
  postgres_db_db_sync:
    file: ../../compose/placeholder-secrets/postgres_db_db_sync
  postgres_db_handle:
    file: ../../compose/placeholder-secrets/postgres_db_handle
  postgres_db_stake_pool:
    file: ../../compose/placeholder-secrets/postgres_db_stake_pool
  postgres_db_wallet_api:
    file: ../../compose/placeholder-secrets/postgres_db_wallet_api
  postgres_password:
    file: ../../compose/placeholder-secrets/postgres_password
  postgres_user:
    file: ../../compose/placeholder-secrets/postgres_user

volumes:
  db-sync-data:
  node-db:
  node-ipc:
