version: '3.9'

x-from-sdk: &from-sdk
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 10
  restart: on-failure

x-logging: &logging
  logging:
    driver: 'json-file'
    options:
      max-size: '400k'
      max-file: '20'

x-projector: &projector
  build:
    context: ../../
    target: projector
  depends_on:
    ogmios:
      condition: service_healthy

x-provider-server: &provider-server
  build:
    args:
      - NETWORK=${NETWORK:-mainnet}
    context: ../../
    target: provider-server
  depends_on:
    cardano-db-sync:
      condition: service_healthy

x-with-postgres: &with-postgres
  depends_on:
    postgres:
      condition: service_healthy
  secrets:
    - postgres_password
    - postgres_user
    - postgres_db
    - postgres_db_asset
    - postgres_db_db_sync
    - postgres_db_handle
    - postgres_db_stake_pool

x-projector-environment: &projector-environment
  API_URL: http://0.0.0.0:3000
  BLOCKS_BUFFER_LENGTH: ${BLOCKS_BUFFER_LENGTH:-10}
  DROP_SCHEMA: ${DROP_PROJECTOR_SCHEMA:-false}
  POSTGRES_HOST: postgres
  POSTGRES_POOL_MAX: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_PORT: 5432
  POSTGRES_USER_FILE: /run/secrets/postgres_user
  SYNCHRONIZE: ${SYNCHRONIZE:-true}

x-provider-server-environment: &provider-server-environment
  API_URL: http://0.0.0.0:3000
  DB_CACHE_TTL: ${DB_CACHE_TTL:-120}
  DISABLE_DB_CACHE: ${DISABLE_DB_CACHE:-false}
  DISABLE_STAKE_POOL_METRIC_APY: ${DISABLE_STAKE_POOL_METRIC_APY:-false}
  ENABLE_METRICS: ${ENABLE_METRICS:-false}
  EPOCH_POLL_INTERVAL: ${EPOCH_POLL_INTERVAL:-500}
  SERVICE_NAMES: ${SERVICE_NAMES:-asset,chain-history,handle,network-info,rewards,stake-pool,tx-submit,utxo}
  SUBMIT_API_URL: ${SUBMIT_API_URL:-http://cardano-submit-api:8090/}
  USE_BLOCKFROST: ${USE_BLOCKFROST:-false}
  USE_SUBMIT_API: ${USE_SUBMIT_API:-false}

x-sdk-environment: &sdk-environment
  LOGGER_MIN_SEVERITY: ${LOGGER_MIN_SEVERITY:-info}
  NETWORK_INFO_PROVIDER_URL: http://provider-server:3000/
  OGMIOS_URL: ws://ogmios:1337
  OVERRIDE_FUZZY_OPTIONS: true
  POSTGRES_DB_FILE_ASSET: /run/secrets/postgres_db_asset
  POSTGRES_DB_FILE_DB_SYNC: /run/secrets/postgres_db_db_sync
  POSTGRES_DB_FILE_HANDLE: /run/secrets/postgres_db_handle
  POSTGRES_DB_FILE_STAKE_POOL: /run/secrets/postgres_db_stake_pool
  POSTGRES_HOST_DB_SYNC: postgres
  POSTGRES_HOST_HANDLE: postgres
  POSTGRES_HOST_STAKE_POOL: postgres
  POSTGRES_POOL_MAX_DB_SYNC: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_POOL_MAX_HANDLE: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_POOL_MAX_STAKE_POOL: ${POSTGRES_POOL_MAX:-10}
  POSTGRES_PASSWORD_FILE_ASSET: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_DB_SYNC: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_HANDLE: /run/secrets/postgres_password
  POSTGRES_PASSWORD_FILE_STAKE_POOL: /run/secrets/postgres_password
  POSTGRES_PORT_DB_SYNC: 5432
  POSTGRES_PORT_HANDLE: 5432
  POSTGRES_PORT_STAKE_POOL: 5432
  POSTGRES_USER_FILE_ASSET: /run/secrets/postgres_user
  POSTGRES_USER_FILE_DB_SYNC: /run/secrets/postgres_user
  POSTGRES_USER_FILE_HANDLE: /run/secrets/postgres_user
  POSTGRES_USER_FILE_STAKE_POOL: /run/secrets/postgres_user
  TOKEN_METADATA_SERVER_URL: https://metadata.world.dev.cardano.org

services:
  cardano-db-sync:
    <<:
      - *logging
      - *with-postgres
    command: ['--config', '/config/cardano-db-sync/config.json', '--socket-path', '/node-ipc/node.socket']
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RESTORE_SNAPSHOT: ${RESTORE_SNAPSHOT:-}
      RESTORE_RECREATE_DB: N
    depends_on:
      ogmios:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/scripts/is-db-synced.sh']
      interval: 5s
      timeout: 1s
      retries: 120
      start_period: 100ms
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.1.0.0}
    restart: on-failure
    stop_signal: SIGINT
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
      - ../../packages/e2e/local-network/scripts:/scripts

  cardano-smash:
    <<:
      - *logging
      - *with-postgres
    image: ghcr.io/intersectmbo/cardano-smash-server:${CARDANO_DB_SYNC_VERSION:-13.1.0.2}
    command: ['--config', '/config/cardano-db-sync/config.json']
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RESTORE_SNAPSHOT: ${RESTORE_SNAPSHOT:-}
      RESTORE_RECREATE_DB: N
      SMASH_USER: ${SMASH_USER:-admin}
      SMASH_PASSWORD: ${SMASH_PASSWORD:-change_m}
    depends_on:
      cardano-db-sync:
        condition: service_healthy
    ports:
      - ${SMASH_PORT:-3100}:3100
    restart: on-failure
    stop_signal: SIGINT
    healthcheck:
      test: ['CMD-SHELL', 'curl -s --fail http://localhost:3100/api/v1/status']

  cardano-node:
    <<: *logging
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.35.5}
    command:
      [
        'run',
        '--config',
        '/config/config.json',
        '--database-path',
        '/db',
        '--socket-path',
        '/ipc/node.socket',
        '--topology',
        '/config/topology.json'
      ]
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc

  ogmios:
    <<: *logging
    image: cardanosolutions/ogmios:v${OGMIOS_VERSION:-5.6.0}
    command:
      ['--host', '0.0.0.0', '--node-socket', '/ipc/node.socket', '--node-config', '/config/cardano-node/config.json']
    healthcheck:
      retries: 2000
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - node-ipc:/ipc

  cardano-submit-api:
    command: --config /config/cardano-submit-api/config.json --listen-address 0.0.0.0 --socket-path /ipc/node.socket $SUBMIT_API_ARGS
    image: inputoutput/cardano-submit-api:${CARDANO_NODE_VERSION:-1.35.5}
    ports:
      - 8090:8090
    restart: on-failure
    stop_signal: SIGINT
    volumes:
      - node-ipc:/ipc

  pg-boss-worker:
    <<:
      - *from-sdk
      - *logging
      - *with-postgres
    build:
      context: ../../
      target: pg-boss-worker
    depends_on:
      stake-pool-projector:
        condition: service_healthy
      cardano-smash:
        condition: service_healthy
    environment:
      <<: *sdk-environment
      API_URL: http://0.0.0.0:3003
      QUEUES: ${QUEUES:-pool-delist-schedule,pool-metadata,pool-metrics,pool-rewards}
      STAKE_POOL_PROVIDER_URL: http://provider-server:3000/
      METADATA_FETCH_MODE: ${METADATA_FETCH_MODE:-direct}
      SMASH_URL: ${SMASH_URL:-http://cardano-smash:3100/api/v1}
    healthcheck:
      test: ['CMD-SHELL', 'curl -s --fail http://localhost:3003/v1.0.0/health']
    ports:
      - ${PG_BOSS_PORT:-4003}:3003

  postgres:
    <<: *logging
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_LOGGING: true
      POSTGRES_DB_FILE: /run/secrets/postgres_db_db_sync
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: on-failure
    secrets:
      - postgres_db_db_sync
      - postgres_password
      - postgres_user
    shm_size: '2gb'

  asset-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_asset
      PROJECTION_NAMES: asset
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'test `curl -fs http://localhost:3000/v1.0.0/health | jq -r ".services[0].projectedTip.blockNo"` -gt 1'
        ]
    ports:
      - ${ASSET_PROJECTOR_PORT:-4006}:3000

  handle-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_handle
      PROJECTION_NAMES: handle
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'test `curl -fs http://localhost:3000/v1.0.0/health | jq -r ".services[0].projectedTip.blockNo"` -gt 1'
        ]
    ports:
      - ${HANDLE_PROJECTOR_PORT:-4004}:3000

  stake-pool-projector:
    <<:
      - *from-sdk
      - *logging
      - *projector
      - *with-postgres
    environment:
      <<:
        - *projector-environment
        - *sdk-environment
      POSTGRES_DB_FILE: /run/secrets/postgres_db_stake_pool
      PROJECTION_NAMES: stake-pool,stake-pool-metadata-job,stake-pool-metrics-job,stake-pool-rewards-job
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'test `curl -fs http://localhost:3000/v1.0.0/health | jq -r ".services[0].projectedTip.blockNo"` -gt 1'
        ]
    ports:
      - ${STAKE_POOL_PROJECTOR_PORT:-4002}:3000

  provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
    ports:
      - ${API_PORT:-4000}:3000

  stake-pool-provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
      SERVICE_NAMES: stake-pool
      USE_TYPEORM_STAKE_POOL_PROVIDER: true
    ports:
      - ${STAKE_POOL_API_PORT:-4010}:3000

  asset-provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
      SERVICE_NAMES: asset
    ports:
      - ${HANDLE_API_PORT:-4014}:3000

  handle-provider-server:
    <<:
      - *from-sdk
      - *logging
      - *provider-server
      - *with-postgres
    environment:
      <<:
        - *sdk-environment
        - *provider-server-environment
      SERVICE_NAMES: handle
    ports:
      - ${HANDLE_API_PORT:-4011}:3000

secrets:
  # Replicates the db-sync secret for historical reasons.
  # When the SDK was using only one database (the db-sync one) the only secret for database name used was this one
  # to be compliant with db-sync image naming.
  # The upstream db-sync Docker image is missing environment variables that allow the consumer to mount into a
  # non-standard path, so we must conform with the hard-coded secret name.
  # As demonstrated here: https://docs.docker.com/compose/use-secrets/#advanced, we could extend the Docker image
  # and define POSTGRES_DB_FILE as the custom path to remove this workaround.
  # See https://github.com/input-output-hk/cardano-db-sync/blob/aed18d1be192bd58d054cdba23758b579dae9f4e/nix/docker.nix#L116
  postgres_db:
    file: ../../compose/placeholder-secrets/postgres_db_db_sync
  postgres_db_asset:
    file: ../../compose/placeholder-secrets/postgres_db_asset
  postgres_db_db_sync:
    file: ../../compose/placeholder-secrets/postgres_db_db_sync
  postgres_db_handle:
    file: ../../compose/placeholder-secrets/postgres_db_handle
  postgres_db_stake_pool:
    file: ../../compose/placeholder-secrets/postgres_db_stake_pool
  postgres_password:
    file: ../../compose/placeholder-secrets/postgres_password
  postgres_user:
    file: ../../compose/placeholder-secrets/postgres_user

volumes:
  db-sync-data:
  node-db:
  node-ipc:
