version: '3.9'

services:
  pg-boss-worker:
    volumes:
      - ../..:/app

  handle-projector:
    volumes:
      - ../..:/app

  provider-server:
    volumes:
      - ../..:/app

  stake-pool-projector:
    volumes:
      - ../..:/app

  stake-pool-provider-server:
    volumes:
      - ../..:/app

  handle-provider-server:
    volumes:
      - ../..:/app

  worker:
    volumes:
      - ../..:/app
