apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    network: preview
    release: dev-preview-cardanojs
  name: dev-preview-cardanojs-backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
    network: preview
    release: dev-preview-cardanojs
