apiVersion: v1
kind: Service
metadata:
  labels:
    app: coingecko-proxy
    network: preview
    release: dev-preview-cardanojs
  name: dev-preview-cardanojs-coingecko-proxy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: coingecko-proxy
    network: preview
    release: dev-preview-cardanojs
