apiVersion: v1
kind: Service
metadata:
  labels:
    app: handle-provider

  name: cardanojs-handle-provider
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: handle-provider
