apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: lace-handle-provider-monitor
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: http
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app: handle-provider
