apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: handle-projector
    network: preview
    release: dev-preview-cardanojs
  name: dev-preview-cardanojs-handle-projector
spec:
  selector:
    matchLabels:
      app: handle-projector
      network: preview
      release: dev-preview-cardanojs
  template:
    metadata:
      labels:
        app: handle-projector
        network: preview
        release: dev-preview-cardanojs
    spec:
      containers:
        - args:
            - start-projector
          env:
            - name: HANDLE_POLICY_IDS
              value: f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a
            - name: LOGGER_MIN_SEVERITY
              value: debug
            - name: NETWORK
              value: preview
            - name: OGMIOS_SRV_SERVICE_NAME
              value: dev-preview-cardano-stack.dev-preview.svc.cluster.local
            - name: POSTGRES_DB
              value: handle
            - name: POSTGRES_HOST
              value: dev-preview-dbsync-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: handle-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: POSTGRES_POOL_MAX
              value: "2"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SSL
              value: "true"
            - name: POSTGRES_SSL_CA_FILE
              value: /tls/ca.crt
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: handle-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: PROJECTION_NAMES
              value: handle
          image: FIXME-ADD-LATEST-IMAGE-REFERENCE
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            timeoutSeconds: 5
          name: handle-projector
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 150Mi
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - mountPath: /tls
              name: tls
      imagePullSecrets:
        - name: dockerconfigjson
      volumes:
        - csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/issuer-name: root-ca
              csi.cert-manager.io/key-usages: client auth
          name: tls
