apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pg-boss-worker
    network: preview
    release: dev-preview-cardanojs
  name: dev-preview-cardanojs-pg-boss-worker
spec:
  selector:
    matchLabels:
      app: pg-boss-worker
      network: preview
      release: dev-preview-cardanojs
  template:
    metadata:
      labels:
        app: pg-boss-worker
        network: preview
        release: dev-preview-cardanojs
    spec:
      containers:
        - args:
            - start-pg-boss-worker
          env:
            - name: LOGGER_MIN_SEVERITY
              value: debug
            - name: NETWORK
              value: preview
            - name: POSTGRES_DB_DB_SYNC
              value: cardano
            - name: POSTGRES_DB_STAKE_POOL
              value: stakepool
            - name: POSTGRES_HOST_DB_SYNC
              value: dev-preview-dbsync-db
            - name: POSTGRES_HOST_STAKE_POOL
              value: dev-preview-dbsync-db
            - name: POSTGRES_PASSWORD_DB_SYNC
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cardano-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: POSTGRES_PASSWORD_STAKE_POOL
              valueFrom:
                secretKeyRef:
                  key: password
                  name: stakepool-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: POSTGRES_POOL_MAX_DB_SYNC
              value: "5"
            - name: POSTGRES_POOL_MAX_STAKE_POOL
              value: "5"
            - name: POSTGRES_PORT_DB_SYNC
              value: "5432"
            - name: POSTGRES_PORT_STAKE_POOL
              value: "5432"
            - name: POSTGRES_SSL_CA_FILE_DB_SYNC
              value: /tls/ca.crt
            - name: POSTGRES_SSL_CA_FILE_STAKE_POOL
              value: /tls/ca.crt
            - name: POSTGRES_SSL_DB_SYNC
              value: "true"
            - name: POSTGRES_SSL_STAKE_POOL
              value: "true"
            - name: POSTGRES_USER_DB_SYNC
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cardano-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: POSTGRES_USER_STAKE_POOL
              valueFrom:
                secretKeyRef:
                  key: username
                  name: stakepool-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: QUEUES
              value: pool-metadata,pool-metrics
            - name: STAKE_POOL_PROVIDER_URL
              value: https://dev-preview-stake-pool.dev-preview.svc.cluster.local/stake-pool
          image: 926093910549.dkr.ecr.us-east-1.amazonaws.com/cardano-services-server:aana7a352vdaz0rs41yhfh3s85inw004
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
          name: pg-boss-worker
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 150Mi
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          startupProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 80
            periodSeconds: 5
          volumeMounts:
            - mountPath: /tls
              name: tls
      imagePullSecrets:
        - name: dockerconfigjson
      volumes:
        - csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/issuer-name: root-ca
              csi.cert-manager.io/key-usages: client auth
          name: tls
