apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: lace-stake-pool-provider-monitor
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /v1.0.0/metrics
      port: http
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app: stake-pool-provider
