apiVersion: v1
kind: Service
metadata:
  labels:
    app: stake-pool-provider

  name: cardanojs-stake-pool-provider
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: stake-pool-provider
