name: Continuous Integration - Side Tests

env:
  TL_DEPTH: ${{ github.event.pull_request.head.repo.fork && '0' || fromJson(vars.TL_DEPTH) }}
  TL_LEVEL: ${{ github.event.pull_request.head.repo.fork && 'info' || vars.TL_LEVEL }}

on:
  pull_request:
  push:
    branches: ['master']
    tags: ['*.*.*']

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: 🔨 Build
        run: |
          yarn install --immutable --inline-builds --mode=skip-build
          yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'

      - name: 🔃 Check for circular dependencies
        run: |
          yarn circular-deps:check

      - name: 🔬 Test
        run: |
          yarn lint
          yarn test:build:verify
          yarn workspace @cardano-sdk/cardano-services test:cli
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
