name: nightly-merge

on:
  workflow_dispatch:
  schedule:
    # Every day 00:00 UTC
    - cron:  '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3
      with:
        # Fetch all history for all tags and branches
        fetch-depth: 0
        ref: nightly

    - name: ⏬ Merge in master
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        # checkout yarn-project.nix to avoid merge conflict
        git checkout origin/master -- yarn-project.nix
        git checkout origin/master -- yarn.lock
        git commit -m "chore: checkout yarn-project.nix and yarn.lock from master" || echo "No changes in yarn-project.nix"
        git merge origin/master
        yarn --mode=skip-build
        git add .
        git commit -m "chore: regenerate yarn-project.nix and yarn.lock" || echo "No changes in yarn-project.nix"
        git push --force
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
